name: Draft-TP
favicon: null
layout_spectrum: 0.96672
typography_spectrum: 0.85572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#353535'
    - '#d7d7d7'
    - '#f7f7f7'
    - '#bcbcbc'
    - '#8e8e8e'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.8823620602488518
purpose: []
